### ISSUE TITLE
Extensions in the wrong place

### ISSUE THREAD

**Issue by okaa-pi** [darkxst/multiple-monitor-panels#1]
Hi, I have a problem with the new version of the extension.
Before, on the "second screen", I had the time in the center of the panel, and the "Activities" on the left.
The other extensions (weather for example) was on the "main screen".

But now, I don't have the time on the second screen, and the other extensions are on the second screen, not on the main.

Here is a screen to illustrate:

http://ompldr.org/vZTZxMw

I don't know if this was planned.
But I think that it would be better to have the extensions on both screen, or just on the main screen, but certainly not on the second.

(Sorry for my english).

**Comment by okaa-pi** [comment]
I didn't say anything! 
I just didn't saw the settings...

**Comment by darkxst** [comment]
I don't think its possible to display extensions on both monitors unfortunately.

You can however configure which monitor the extensions display on in the preferences tool
