### ISSUE TITLE
Maximization Problems on (some) Secondary Displays

### ISSUE THREAD

**Issue by wcunning** [darkxst/multiple-monitor-panels#3]
I have 4 monitors, in the following orientation: one horizontal at 1920x1080 -> 1200x1920 -> 1200x1920 -> 1920x1080, with the tops of each monitor aligned. Mediocre ASCII art follows this bug report for the visually inclined. My issue is that windows maximized on the middle two are not being limited by the panels on those monitors. I am using the AMD proprietary graphics drivers, if that makes a difference. 

---

[____]|     ||     |[____]
         |**_||**_|

**Comment by darkxst** [comment]
If you set your primary monitor on one of the rotated monitors, does it work correctly when maximising windows?

**Comment by wcunning** [comment]
Yes, but not if I move primary status away. Also, the non-rotated displays work fine whether they're primary or not.

**Comment by darkxst** [comment]
I tested this on my NVIDIA system and cant reproduce it.  It may be a bug in the AMD Driver, perhaps you can confirm this, by testing with radeon and see if that works.

**Comment by wcunning** [comment]
I found the issue only after poking into xorg.conf. Apparently the AMD setup utility doesn't attempt to snap monitors to the same level, so the screen that was defining where the panels went was at "0 18" and the middle two displays were at "1920 2" and "3120 2". Changing all of those to be at "x 0" made everything work properly.
