### ISSUE TITLE
can't install in gnome 3.4.1

### ISSUE THREAD

**Issue by testopiano** [darkxst/multiple-monitor-panels#6]
Hi, 
I can't install the extension in gnome 3.4.1 debian sid. Any hint?
Is the ext. compatible with my gnome version?

Thanks

**Comment by darkxst** [comment]
master is only compatible with 3.6 currently.

this one will work with 3.4 though https://github.com/darkxst/multiple-monitor-panels/tree/gnome-3.4

**Comment by testopiano** [comment]
Thanks a lot! it works perfectly.
Just a question, as far as you know is there a way or extension to have different workspaces on the extended monitor?

thanks again
good extension!

**Comment by darkxst** [comment]
apart from 'workspaces only on primary', no other options exist currently.

It would probably be possible  to unlink the workspaces, however I have no idea how you would go about controlling it. I imagine it would end up getting confusing if you stuck with the keyboard shortcuts and just based it off mouse position.

**Comment by testopiano** [comment]
Thanks a lot
