### ISSUE TITLE
Display Workspace Switchers checkbox not working

### ISSUE THREAD

**Issue by goehle** [darkxst/multiple-monitor-panels#9]
When I uncheck "Display Workspace Switchers" on the preferences page I expect that the workspace switchers on the secondary monitor should dissapear.   As it stands unchecking this option doesn't seem to do anything.  

(I could be interpreting its function wrong, however, Workspace Switchers on left does move the secondary monitor switchers to the opposite side as expected.)

**Comment by darkxst** [comment]
Currrently enabling/disabling workspace switchers, requires to restart gnome-shell (or reload the extension). I will fix this setting to be real-time in a future version.

**Comment by goehle** [comment]
Ah, OK.  In the meantime I recommend putting some "(shell restart required)" text next to the option name.  At least, it wasn't obvious to me that it was necessary.

**Comment by goehle** [comment]
FYI, 
I've tried restarting the gnome-shell and unloading/reloading the plugin and the Display Workspace Switchers still doesn't seem to do anything.

**Comment by benoit2600** [comment]
I've the same problem, restarting the session change nothing. I use gnome-shell 3.6 on ubuntu 12.04. On the secondary  screen, it can only have one desktop ( the default gnome-shell configuration, I don't remember the name of this feature)

**Comment by darkxst** [comment]
@benoit2600 you need to set  "workspaces only on primary" to off in gnome tweak tool, or the workspace switchers wont work on additional monitors.

**Comment by benoit2600** [comment]
Yes, I know that, and I don't want multiple Workspace on my secundary monitor. But the Display Workspace Switchers  shows on it, even with the checkbox on false.

**Comment by goehle** [comment]
Works as intended in latest version
